### ISSUE TITLE
I don't understand this part .. can anyone help please?

### ISSUE THREAD

**Issue by boramriganka** [alex83130/advanced-react-patterns#2]
Hello Alex, it was great reading about the different patterns. You explained them very well. Good Job.
I am still a beginner bdw, would you mind explain what does the below lines do ? (This is from Counter component in compound component part)

![carbon (3)](https://user-images.githubusercontent.com/42547729/133417750-3b9619d1-0f2d-497a-b1e4-c84479000741.png)

**Comment by alexis-regnaud** [comment]
Hi boramriganka, thanks for the feedback, it's really appreciated.

**At First, just take the `useEffect` without the `firstMounded` logic:**

```
  useEffect(() => {
      onChange && onChange(count);
  }, [count, onChange]);
```

A `useEffect` will trigger a side-effect every time a component is re-render and if one of the Array Depency was changed. That includes also the very first time when your Component is mounted.

So concretely here the side-effect will be triggered at the first render **and** every time that `count` or `onChange` are changed (Which means every time when the user click on the `Increment` or `Decrement` button)

This is pretty bad in our case because we don't want to call the `onChange` callback before that the User really starts to interact with the component.

**It's why we implement firstMounded logic:** 

```
  const firstMounded = useRef(true);
  useEffect(() => {
    if (!firstMounded.current) {
      onChange && onChange(count);
    }
    firstMounded.current = false;
  }, [count, onChange]);
```
This  are the different steps our code will go through :
1) `firstMounded` is initialised to `true`
2) The side-effect is executed right after the first render:
a. `onChange` isn't called because it doesn't pass the condition (`firstMounded === false`)
b. `firstMounted` is changed for false
3) The User clicks on the Increment button
4) The side-effect is executed right after the component re-render
a. `onChange` is called because it passes the condition (`firstMounded === false`)

Now we have a component that will call `onChange` only when the user clicks on the Increment or the Decrement button.

PS: if you put some `console.log` you  should clearly see both behaviors: 
```
  const firstMounded = useRef(true);
  useEffect(() => {
    console.log("Side-effect A")
    if (!firstMounded.current) {
      console.log("Side-effect B")
      onChange && onChange(count);
    }
    firstMounded.current = false;
  }, [count, onChange]);
```

**Comment by alexis-regnaud** [comment]
Btw don't have that whole `useEffect` logic and just call `onChange` from `handleIncrement` and `handleDecrement` would work as well.

![Screen Shot 2021-09-16 at 6 12 42 PM](https://user-images.githubusercontent.com/15250423/133692498-e923aaef-8acb-4845-955e-d379887b1cf4.png)

**Comment by boramriganka** [comment]
Thank you very much . My doubt is completely resolved now.
